# Generated by Django 5.2.5 on 2025-09-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_ordermodel_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='delivery_change',
            new_name='delivery_charge',
        ),
    ]
