# Generated by Django 5.2.5 on 2025-09-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_rename_delivery_change_ordermodel_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='location_choice',
            field=models.CharField(choices=[('ID', 'Inside Dhaka'), ('OD', 'Outside Dhaka')], default='Inside Dhaka'),
        ),
    ]
