# Generated by Django 5.2.5 on 2025-09-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(blank=True, default='Nothing', null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_method',
            field=models.CharField(blank=True, default='Nothing', max_length=100, null=True),
        ),
    ]
