# Generated by Django 5.2.5 on 2025-09-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_ordermodel_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(default='Nothing'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_method',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
