# Generated by Django 5.2.5 on 2025-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_ordermodel_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
