# Generated by Django 5.2.5 on 2025-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_ordermodel_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submit', 'Submit'), ('Completed', 'Completed'), ('Cancle', 'Cancle')], default='Pending', null=True),
        ),
    ]
