# Generated by Django 5.2.5 on 2025-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='location_choice',
            field=models.CharField(choices=[('Inside Dhaka', 'Inside Dhaka'), ('Inside Dhaka', 'Outside Dhaka')], default='Inside Dhaka'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', null=True),
        ),
    ]
