# Generated by Django 5.2.5 on 2025-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_ordermodel_location_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processing', null=True),
        ),
    ]
