# Generated by Django 5.2.5 on 2025-09-18 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('number', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_title', models.CharField(blank=True, null=True)),
                ('features_name', models.JSONField(blank=True, default=list)),
                ('second_title', models.CharField(blank=True, null=True)),
                ('benefits_name', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FontSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('small_title', models.CharField(blank=True, null=True)),
                ('big_title', models.CharField()),
                ('font_asset', models.ImageField(default='not-found.jpg', upload_to='font_asset/')),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('phone', models.CharField(default='Nothing', max_length=14)),
                ('address', models.CharField(default='Nothing', max_length=200)),
                ('comment', models.TextField(blank=True, default='Nothing', null=True)),
                ('quantity', models.CharField(default='Nothing')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submit', 'Submit'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Pending', null=True)),
                ('product_name', models.CharField(default='Nothing', max_length=250)),
                ('delivery_change', models.CharField(default=0)),
                ('price', models.CharField(default=0)),
                ('payment_method', models.CharField(default='Nothing', max_length=60)),
                ('transaction_method', models.CharField(default='Nothing', max_length=100)),
                ('transaction_id', models.CharField(default='Nothing')),
                ('location_choice', models.CharField(choices=[('ID', 'Inside Dhaka'), ('OD', 'Outside Dhaka')], default='1')),
                ('payment_choice', models.CharField(choices=[('CD', 'Cash on Delivary'), ('OP', 'Online Payment')], default='1')),
                ('order_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('photo_asset', models.ImageField(blank=True, default='not-found.jpg', null=True, upload_to='photo_asset/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('quantity', models.CharField(default=0)),
                ('price', models.CharField(default=0)),
                ('insideDhaka', models.CharField(default=0)),
                ('outsideDhaka', models.CharField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GellerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('photos', models.ManyToManyField(blank=True, related_name='gellery', to='page.photo')),
            ],
        ),
    ]
