# Generated by Django 5.2.5 on 2025-09-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_ordermodel_location_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
