# Generated by Django 5.2.5 on 2025-09-18 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_delete_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('phone', models.CharField(default='Nothing', max_length=14)),
                ('address', models.CharField(default='Nothing', max_length=200)),
                ('comment', models.TextField(blank=True, default='Nothing', null=True)),
                ('quantity', models.CharField(default='Nothing')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submit', 'Submit'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Pending', null=True)),
                ('product_name', models.CharField(default='Nothing', max_length=250)),
                ('price', models.CharField(default=0)),
                ('delivery_charge', models.CharField(default=0)),
                ('total_price', models.CharField(default=0)),
                ('payment_method', models.CharField(choices=[('CD', 'Cash on Delivary'), ('OP', 'Online Payment')], default='Nothing', max_length=60)),
                ('transaction_method', models.CharField(default='Nothing', max_length=100)),
                ('transaction_id', models.CharField(default='Nothing')),
                ('location_choice', models.CharField(choices=[('ID', 'Inside Dhaka'), ('OD', 'Outside Dhaka')], default='Inside Dhaka')),
                ('order_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
